---
- hosts: localhost
  become: yes

  vars:
    bitbucket_ebs_path: "/opt/ebs"

  pre_tasks:
    - name: retrieve instance metadata
      ec2_metadata_facts:

    - ec2_vol:
        region: eu-west-1
        id: "{{ ansible_local.ebs.id }}"
        instance: "{{ ansible_ec2_instance_id }}"
        device_name: /dev/xvdg

    - filesystem:
        fstype: ext4
        dev: /dev/xvdg

    - name: Mount up device by label
      mount:
        path: "{{ bitbucket_ebs_path }}"
        src: "/dev/xvdg"
        fstype: "ext4"
        state: mounted

  roles:
    - bitbucket