---
- hosts: localhost
  become: yes

  vars:
    bitbucket_ebs_path: "/opt/ebs"
    bitbucket_ebs_device: "/dev/xvdg"
    bitbucket_ebs_fstype: "ext4"

  pre_tasks:
    - name: Retrieve instance metadata
      ec2_metadata_facts:

    - name: Claim ebs volume
      ec2_vol:
        region: eu-west-1
        id: "{{ ansible_local.ebs.id }}"
        instance: "{{ ansible_ec2_instance_id }}"
        device_name: "{{ bitbucket_ebs_device }}"

    - name: Create volume filesystem
      filesystem:
        fstype: "{{ bitbucket_ebs_fstype }}"
        dev: "{{ bitbucket_ebs_device }}"

    - name: Mount volume
      mount:
        path: "{{ bitbucket_ebs_path }}"
        src: "{{ bitbucket_ebs_device }}"
        fstype: "{{ bitbucket_ebs_fstype }}"
        state: mounted

  roles:
    - bitbucket